version: '3'

networks:
    back:

services:
    steps:
        build: ./steps
        ports:
            - "3080:3080"
        restart: always
        depends_on:
            - mongo
        networks:
            - back
        #volumes:
        #    - ./vol:/app/vol
    mongo:
        image: mongo
        networks:
            - back
