version: '3'

services:
    steps:
        build: ./steps
        ports:
            - "3080:3080"
        restart: always
        depends_on:
            - mongo
        volumes:
            - ./vol:/app/vol
    mongo:
        image: mongo