version: '3'

networks:
    back:

services:
    app:
        build: ./app
        ports:
            - "15014:80"
        restart: always
        depends_on:
            - db
        networks:
            - back
    db:
        image: mongo
        restart: always
        networks:
            - back
